### ISSUE TITLE
Install modules from pip?

### ISSUE THREAD

**Issue by jackjennings** [typesupply/roborepl#2]
I know the Frederik has made it so that modules installed in system python are picked up by RoboFont, but being able to install pip packages in an isolated spot would be a nice alternative.

**Comment by jackjennings** [comment]
Could be out of scope or more suited for a standalone extension I guess.

**Comment by typesupply** [comment]
Yeah. That's probably out of the scope of this. What do you think @typemytype?

**Comment by colinmford** [comment]
Since @typemytype added this to RF3, I think this might be solved. https://robofont.com/documentation/workspace/package-installer/
