### ISSUE TITLE
Export Theme/Settings?

### ISSUE THREAD

**Issue by colinmford** [typesupply/roborepl#20]
Hi @typesupply,

Recently got _really_ into using RoboREPL (I just typed "f=CurrentFont()" in a new script window one too many times and snapped).

I've customized it with startup variables and a theme to match my Terminal. However, I also work on two computers often, so I was wondering if there was a way to export all the user-defined settings, and import it to another computer?

If you're open to the idea and short on time I could try to make a pull request.

**Comment by typesupply** [comment]
There's `settings.saveTheme` and `settings.loadTheme` but [those only handle colors](https://github.com/typesupply/roborepl/blob/master/RoboREPL.roboFontExt/lib/roboREPL.py#L300). The rest of the configuration is accessible via the [settings API](https://github.com/typesupply/roborepl/blob/master/RoboREPL.roboFontExt/lib/roboREPL.py#L165), but that's not super useful for what you need. Maybe the settings object could have a `printConfiguration` method that outputs a script that could be copied, saved and executed on another device? For example:

```python
settings.bannerGreeting =  "Would you like to play a game?"
settings.colorBackground =  (0, 0, 0, 0.8)
settings.colorCode =  (0, 1, 0, 1)
settings.colorStderr =  (1, 0, 0, 1)
settings.colorStdout =  (1, 1, 1, 1)
settings.fontName =  "QueueMono-Light"
settings.fontSize =  15
settings.showInvisibleCharacters =  False
settings.startupCode = """CF = CurrentFont
CG = CurrentGlyph
AF = AllFonts
OF = OpenFont
NF = NewFont

# ------------
# Test Install
# ------------

def Install():
    for f in AF():
        f.testInstall()

# ----------
# Pasteboard
# ----------

from AppKit import NSPasteboard, NSPasteboardTypeString

def toclipboard(text):
    pasteboard = NSPasteboard.generalPasteboard()
    pasteboard.declareTypes_owner_([NSPasteboardTypeString], None)
    pasteboard.setString_forType_(text, NSPasteboardTypeString)

def fromclipboard():
    pasteboard = NSPasteboard.generalPasteboard()
    text = pasteboard.stringForType_(NSPasteboardTypeString)
    return text
"""

settings.tabString = "   "
settings.windowHeight = 24
settings.windowWidth = 80
```

I made this with this hacky hack:

```python
>>> for attr in sorted(dir(settings)):
...   if attr.startswith("_"): continue
...   print("settings." + attr + " = ", getattr(settings, attr))
```

If you'd want to build something to do this, work with JSON or whatever, that would be great!
