### ISSUE TITLE
" is converted to “

### ISSUE THREAD

**Issue by jackjennings** [typesupply/roborepl#5]
When I try to type e.g. `settings.loadTheme("classic")` I get a syntax error because my system automatically converts these quotes to typographic variants

**Comment by typesupply** [comment]
Hm. I'll have to look to see if I can disable those within the editor.

**Comment by typesupply** [comment]
[This needs to be set.](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSTextView_Class/index.html#//apple_ref/occ/instp/NSTextView/automaticQuoteSubstitutionEnabled)
